### ISSUE TITLE
enhance PSD shape layer translation (using SVG shape object)

### ISSUE THREAD

**Issue by ichiro-arai** [kyamagu/psd2svg#10]
I think the following `shape` layer handling is not executed, because the previous `elif` clause is executed. (The reason is the majority of shapes has (width, height) > (0, 0))

https://github.com/kyamagu/psd2svg/blob/75c12767fb46c278b575b9dce7b8473a7e548da2/src/psd2svg/converter/core.py#L148

I think if the handling is enhanced, PSD->SVG translation will become better.

(But only reordering the clauses didn't work...!)

**Comment by kyamagu** [comment]
@ichiro-arai This part should be definitely refactored. The code is from when there was not `ShapeLayer` class.
